### ISSUE TITLE
TOB Damage Counter NPE

### ISSUE THREAD

**Issue by Nightfirecat** [Trevor159/runelite-external-plugins#28]
```
2021-12-02 13:22:05 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at gg.trevor.tobdamage.TobDamageCounterPlugin.onGraphicChanged(TobDamageCounterPlugin.java:341)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
	at jk.w(jk.java:48164)
	at client.ho(client.java:7122)
	at client.en(client.java:3304)
	at client.h(client.java:1540)
	at ai.q(ai.java:387)
	at ai.run(ai.java:366)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Trevor159** [comment]
This plugin is now maintained by @aronson here https://github.com/aronson/runelite-external-plugins
